#!/usr/bin/env node
var fs = require('fs')
var path = require('path')
var runSeries = require('run-series')
var lamos = require('lamos')
var AJV = require('ajv')

var ajv = new AJV()
var validate = ajv.compile(require('./schema'))

var error = false

fs.readdir('cases', function (error, entries) {
  if (error) {
    console.error(error)
    process.exit(1)
  }
  runSeries(
    entries.map(function (entry) {
      return function (done) {
        var file = path.join('cases', entry)
        fs.readFile(file, 'utf8', function (error, text) {
          var parsed
          try {
            parsed = lamos.parse(text)
          } catch (error) {
            return done(error)
          }
          validate(parsed)
          var errors = validate.errors
          if (errors && errors.length !== 0) {
            error = true
            console.error(file + ':')
            console.error(errors)
          }
          done()
        })
      }
    }),
    function (error) {
      if (error) {
        console.error(error)
        process.exit(1)
      }
      process.exit(error ? 1 : 0)
    }
  )
})
